// GoodSpan Seasons, practice catalogue
// Each practice: { level: 'gentle'|'moderate'|'deep', text, source }

export const LEVELS = [
  {
    id: 'gentle',
    name: 'Gentle',
    summary: 'A soft entry into the season',
    desc: 'Small, achievable shifts. Build the habit without pressure and let it settle into your days.',
  },
  {
    id: 'moderate',
    name: 'Moderate',
    summary: 'A meaningful step up',
    desc: 'Consistent daily practice and a real commitment to change across the full thirty days.',
  },
  {
    id: 'deep',
    name: 'Deep',
    summary: 'Full, documented commitment',
    desc: 'Transformative practice, tracked, refined, and shared openly with your Circle.',
  },
];

export const SEASONS = [
  {
    id: 'sleep',
    name: 'GoodSleep',
    tagline: 'Rest as the foundation of a long life',
    blurb: 'Rebuild the rhythm, calm, and darkness your body needs to recover each night.',
    accent: 'oklch(0.4 0.09 158)',
    accent2: 'oklch(0.48 0.115 150)',
    soft: 'oklch(0.95 0.05 155)',
    note: 'These practices build healthier sleep habits in the general population — they are not a treatment for diagnosed insomnia. If you live with a sleep disorder, treat this as a complement to professional care, not a replacement.',
    categories: [
      { name: `Circadian Alignment`, practices: [
        { level: 'gentle', text: `5 min outdoors within 1 hour of waking`, source: `Tähkämö, L., Partonen, T., & Pesonen, A.-K. (2019). Systematic review of light exposure impact on human circadian rhythm. Chronobiology International, 36(2), 151-170. https://doi.org/10.1080/07420528.2018.1527773
Brown, T. M. et al. (2022). Recommendations for daytime, evening, and nighttime indoor light exposure to best support physiology, sleep, and wakefulness in healthy adults. PLOS Biology, 20(3), e3001571. https://doi.org/10.1371/journal.pbio.3001571` },
        { level: 'moderate', text: `10–15 min outdoors every day`, source: `Tähkämö, L., Partonen, T., & Pesonen, A.-K. (2019). Systematic review of light exposure impact on human circadian rhythm. Chronobiology International, 36(2), 151-170. https://doi.org/10.1080/07420528.2018.1527773
Brown, T. M. et al. (2022). Recommendations for daytime, evening, and nighttime indoor light exposure to best support physiology, sleep, and wakefulness in healthy adults. PLOS Biology, 20(3), e3001571. https://doi.org/10.1371/journal.pbio.3001571` },
        { level: 'deep', text: `20–30 min outdoors`, source: `Tähkämö, L., Partonen, T., & Pesonen, A.-K. (2019). Systematic review of light exposure impact on human circadian rhythm. Chronobiology International, 36(2), 151-170. https://doi.org/10.1080/07420528.2018.1527773
Brown, T. M. et al. (2022). Recommendations for daytime, evening, and nighttime indoor light exposure to best support physiology, sleep, and wakefulness in healthy adults. PLOS Biology, 20(3), e3001571. https://doi.org/10.1371/journal.pbio.3001571` },
        { level: 'gentle', text: `Bedtime within 60 min`, source: `Chaput, J.-P. et al. (2020). Sleep timing, sleep consistency, and health in adults: A systematic review. Applied Physiology, Nutrition, and Metabolism, 45(10, Suppl. 2), S232-S247. https://doi.org/10.1139/apnm-2020-0032
Windred, D. P. et al. (2024). Sleep regularity is a stronger predictor of mortality risk than sleep duration: A prospective cohort study. Sleep, 47(1), zsad253. https://doi.org/10.1093/sleep/zsad253` },
        { level: 'moderate', text: `Bedtime + wake time within 45 min`, source: `Chaput, J.-P. et al. (2020). Sleep timing, sleep consistency, and health in adults: A systematic review. Applied Physiology, Nutrition, and Metabolism, 45(10, Suppl. 2), S232-S247. https://doi.org/10.1139/apnm-2020-0032
Windred, D. P. et al. (2024). Sleep regularity is a stronger predictor of mortality risk than sleep duration: A prospective cohort study. Sleep, 47(1), zsad253. https://doi.org/10.1093/sleep/zsad253` },
        { level: 'deep', text: `Bedtime + wake time within 30 min`, source: `Chaput, J.-P. et al. (2020). Sleep timing, sleep consistency, and health in adults: A systematic review. Applied Physiology, Nutrition, and Metabolism, 45(10, Suppl. 2), S232-S247. https://doi.org/10.1139/apnm-2020-0032
Windred, D. P. et al. (2024). Sleep regularity is a stronger predictor of mortality risk than sleep duration: A prospective cohort study. Sleep, 47(1), zsad253. https://doi.org/10.1093/sleep/zsad253` },
        { level: 'gentle', text: `Dim lights 1 hour before bed`, source: `Cajochen, C. et al. (2022). Influence of evening light exposure on polysomnographically assessed night-time sleep: A systematic review with meta-analysis. Lighting Research & Technology, 54(6), 609-624. https://doi.org/10.1177/14771535221078765
Phillips, A. J. K. et al. (2019). High sensitivity and interindividual variability in the response of the human circadian system to evening light. PNAS, 116(24), 12019-12024. https://doi.org/10.1073/pnas.1901824116` },
        { level: 'moderate', text: `Avoid bright overhead lights 2 hours before bed`, source: `Cajochen, C. et al. (2022). Influence of evening light exposure on polysomnographically assessed night-time sleep: A systematic review with meta-analysis. Lighting Research & Technology, 54(6), 609-624. https://doi.org/10.1177/14771535221078765
Phillips, A. J. K. et al. (2019). High sensitivity and interindividual variability in the response of the human circadian system to evening light. PNAS, 116(24), 12019-12024. https://doi.org/10.1073/pnas.1901824116` },
        { level: 'deep', text: `Create a low-light evening routine`, source: `Cajochen, C. et al. (2022). Influence of evening light exposure on polysomnographically assessed night-time sleep: A systematic review with meta-analysis. Lighting Research & Technology, 54(6), 609-624. https://doi.org/10.1177/14771535221078765
Phillips, A. J. K. et al. (2019). High sensitivity and interindividual variability in the response of the human circadian system to evening light. PNAS, 116(24), 12019-12024. https://doi.org/10.1073/pnas.1901824116` },
      ] },
      { name: `Sleep Pressure`, practices: [
        { level: 'gentle', text: `20-min walk`, source: `Kredlow, M. A. et al. (2015). The effects of physical activity on sleep: A meta-analytic review. Journal of Behavioral Medicine, 38(3), 427-449. https://doi.org/10.1007/s10865-015-9617-6
Bull, F. C. et al. (2020). World Health Organization 2020 guidelines on physical activity and sedentary behaviour. British Journal of Sports Medicine, 54(24), 1451-1462. https://doi.org/10.1136/bjsports-2020-102955` },
        { level: 'moderate', text: `30 min moderate activity`, source: `Kredlow, M. A. et al. (2015). The effects of physical activity on sleep: A meta-analytic review. Journal of Behavioral Medicine, 38(3), 427-449. https://doi.org/10.1007/s10865-015-9617-6
Bull, F. C. et al. (2020). World Health Organization 2020 guidelines on physical activity and sedentary behaviour. British Journal of Sports Medicine, 54(24), 1451-1462. https://doi.org/10.1136/bjsports-2020-102955` },
        { level: 'deep', text: `Meet WHO activity guidelines`, source: `Kredlow, M. A. et al. (2015). The effects of physical activity on sleep: A meta-analytic review. Journal of Behavioral Medicine, 38(3), 427-449. https://doi.org/10.1007/s10865-015-9617-6
Bull, F. C. et al. (2020). World Health Organization 2020 guidelines on physical activity and sedentary behaviour. British Journal of Sports Medicine, 54(24), 1451-1462. https://doi.org/10.1136/bjsports-2020-102955` },
        { level: 'gentle', text: `No caffeine after 4 pm`, source: `Gardiner, C. et al. (2023). The effect of caffeine on subsequent sleep: A systematic review and meta-analysis. Sleep Medicine Reviews, 69, 101764. https://doi.org/10.1016/j.smrv.2023.101764
Drake, C. et al. (2013). Caffeine effects on sleep taken 0, 3, or 6 hours before going to bed. Journal of Clinical Sleep Medicine, 9(11), 1195-1200. https://doi.org/10.5664/jcsm.3170` },
        { level: 'moderate', text: `No caffeine after 2 pm`, source: `Gardiner, C. et al. (2023). The effect of caffeine on subsequent sleep: A systematic review and meta-analysis. Sleep Medicine Reviews, 69, 101764. https://doi.org/10.1016/j.smrv.2023.101764
Drake, C. et al. (2013). Caffeine effects on sleep taken 0, 3, or 6 hours before going to bed. Journal of Clinical Sleep Medicine, 9(11), 1195-1200. https://doi.org/10.5664/jcsm.3170` },
        { level: 'deep', text: `Adjust intake to your bedtime`, source: `Gardiner, C. et al. (2023). The effect of caffeine on subsequent sleep: A systematic review and meta-analysis. Sleep Medicine Reviews, 69, 101764. https://doi.org/10.1016/j.smrv.2023.101764
Drake, C. et al. (2013). Caffeine effects on sleep taken 0, 3, or 6 hours before going to bed. Journal of Clinical Sleep Medicine, 9(11), 1195-1200. https://doi.org/10.5664/jcsm.3170` },
        { level: 'gentle', text: `Nap <30 min`, source: `Faraut, B. et al. (2017). Napping: A public health issue. From epidemiological to laboratory studies. Sleep Medicine Reviews, 35, 85-100. https://doi.org/10.1016/j.smrv.2016.09.002` },
        { level: 'moderate', text: `Nap before 3 pm`, source: `Faraut, B. et al. (2017). Napping: A public health issue. From epidemiological to laboratory studies. Sleep Medicine Reviews, 35, 85-100. https://doi.org/10.1016/j.smrv.2016.09.002` },
        { level: 'deep', text: `Nap only when needed`, source: `Faraut, B. et al. (2017). Napping: A public health issue. From epidemiological to laboratory studies. Sleep Medicine Reviews, 35, 85-100. https://doi.org/10.1016/j.smrv.2016.09.002` },
      ] },
      { name: `Wind Down`, practices: [
        { level: 'gentle', text: `Slow breathing: 2 min before bed`, source: `Edinger, J. D. et al. (2021). Behavioral and psychological treatments for chronic insomnia disorder in adults: An AASM clinical practice guideline. Journal of Clinical Sleep Medicine, 17(2), 255-262. https://doi.org/10.5664/jcsm.8986
Kuula, L. et al. (2020). The effects of presleep slow breathing and music listening on polysomnographic sleep measures: A pilot trial. Scientific Reports, 10, 7427. https://doi.org/10.1038/s41598-020-64218-7` },
        { level: 'moderate', text: `Slow breathing: 5 min before bed`, source: `Edinger, J. D. et al. (2021). Behavioral and psychological treatments for chronic insomnia disorder in adults: An AASM clinical practice guideline. Journal of Clinical Sleep Medicine, 17(2), 255-262. https://doi.org/10.5664/jcsm.8986
Kuula, L. et al. (2020). The effects of presleep slow breathing and music listening on polysomnographic sleep measures: A pilot trial. Scientific Reports, 10, 7427. https://doi.org/10.1038/s41598-020-64218-7` },
        { level: 'deep', text: `Slow breathing: 10 min before bed`, source: `Edinger, J. D. et al. (2021). Behavioral and psychological treatments for chronic insomnia disorder in adults: An AASM clinical practice guideline. Journal of Clinical Sleep Medicine, 17(2), 255-262. https://doi.org/10.5664/jcsm.8986
Kuula, L. et al. (2020). The effects of presleep slow breathing and music listening on polysomnographic sleep measures: A pilot trial. Scientific Reports, 10, 7427. https://doi.org/10.1038/s41598-020-64218-7` },
        { level: 'gentle', text: `Progressive muscle relaxation: 5 min`, source: `Simon, K. C. et al. (2022). Progressive muscle relaxation increases slow-wave sleep during a daytime nap. Journal of Sleep Research, 31(5), e13574. https://doi.org/10.1111/jsr.13574
Donato, K. O. et al. Progressive muscle relaxation technique improves sleep quality and mental health: A systematic review and meta-analysis of RCTs. Journal of Psychosomatic Research, 203, 112563. https://doi.org/10.1016/j.jpsychores.2026.112563` },
        { level: 'moderate', text: `Progressive muscle relaxation: 10 min`, source: `Simon, K. C. et al. (2022). Progressive muscle relaxation increases slow-wave sleep during a daytime nap. Journal of Sleep Research, 31(5), e13574. https://doi.org/10.1111/jsr.13574
Donato, K. O. et al. Progressive muscle relaxation technique improves sleep quality and mental health: A systematic review and meta-analysis of RCTs. Journal of Psychosomatic Research, 203, 112563. https://doi.org/10.1016/j.jpsychores.2026.112563` },
        { level: 'deep', text: `Progressive muscle relaxation: a full nightly routine`, source: `Simon, K. C. et al. (2022). Progressive muscle relaxation increases slow-wave sleep during a daytime nap. Journal of Sleep Research, 31(5), e13574. https://doi.org/10.1111/jsr.13574
Donato, K. O. et al. Progressive muscle relaxation technique improves sleep quality and mental health: A systematic review and meta-analysis of RCTs. Journal of Psychosomatic Research, 203, 112563. https://doi.org/10.1016/j.jpsychores.2026.112563` },
        { level: 'gentle', text: `Brain dump: write down one task for tomorrow`, source: `Scullin, M. K. et al. (2018). The effects of bedtime writing on difficulty falling asleep. Journal of Experimental Psychology: General, 147(1), 139-146. https://doi.org/10.1037/xge0000374` },
        { level: 'moderate', text: `Brain dump: write down your top 3 priorities for tomorrow`, source: `Scullin, M. K. et al. (2018). The effects of bedtime writing on difficulty falling asleep. Journal of Experimental Psychology: General, 147(1), 139-146. https://doi.org/10.1037/xge0000374` },
        { level: 'deep', text: `Brain dump: a 5-minute written cognitive offload before bed`, source: `Scullin, M. K. et al. (2018). The effects of bedtime writing on difficulty falling asleep. Journal of Experimental Psychology: General, 147(1), 139-146. https://doi.org/10.1037/xge0000374` },
        { level: 'gentle', text: `Relaxing music: 5 min before bed`, source: `Jespersen, K. V. et al. (2022). Listening to music for insomnia in adults. Cochrane Database of Systematic Reviews, 2022(8), CD010459. https://doi.org/10.1002/14651858.CD010459.pub3` },
        { level: 'moderate', text: `Relaxing music: 10 min before bed`, source: `Jespersen, K. V. et al. (2022). Listening to music for insomnia in adults. Cochrane Database of Systematic Reviews, 2022(8), CD010459. https://doi.org/10.1002/14651858.CD010459.pub3` },
        { level: 'deep', text: `Relaxing music: a full sleep playlist as you wind down`, source: `Jespersen, K. V. et al. (2022). Listening to music for insomnia in adults. Cochrane Database of Systematic Reviews, 2022(8), CD010459. https://doi.org/10.1002/14651858.CD010459.pub3` },
      ] },
      { name: `Sleep Environment`, practices: [
        { level: 'gentle', text: `Keep the bedroom at a comfortable temperature`, source: `Baniassadi, A. et al. (2023). Nighttime ambient temperature and sleep in community-dwelling older adults. Science of the Total Environment, 899, 165623. https://doi.org/10.1016/j.scitotenv.2023.165623` },
        { level: 'moderate', text: `18–20°C if possible`, source: `Baniassadi, A. et al. (2023). Nighttime ambient temperature and sleep in community-dwelling older adults. Science of the Total Environment, 899, 165623. https://doi.org/10.1016/j.scitotenv.2023.165623` },
        { level: 'deep', text: `Keep bedroom temperature consistently optimised, night after night`, source: `Baniassadi, A. et al. (2023). Nighttime ambient temperature and sleep in community-dwelling older adults. Science of the Total Environment, 899, 165623. https://doi.org/10.1016/j.scitotenv.2023.165623` },
        { level: 'gentle', text: `Close curtains`, source: `Brown, T. M. et al. (2022). Recommendations for daytime, evening, and nighttime indoor light exposure. PLOS Biology, 20(3), e3001571. https://doi.org/10.1371/journal.pbio.3001571` },
        { level: 'moderate', text: `Remove light sources`, source: `Brown, T. M. et al. (2022). Recommendations for daytime, evening, and nighttime indoor light exposure. PLOS Biology, 20(3), e3001571. https://doi.org/10.1371/journal.pbio.3001571` },
        { level: 'deep', text: `Complete darkness`, source: `Brown, T. M. et al. (2022). Recommendations for daytime, evening, and nighttime indoor light exposure. PLOS Biology, 20(3), e3001571. https://doi.org/10.1371/journal.pbio.3001571` },
        { level: 'gentle', text: `Reduce one noise source`, source: `Basner, M., & McGuire, S. (2018). WHO Environmental Noise Guidelines for the European Region: A systematic review on environmental noise and effects on sleep. IJERPH, 15(3), 519. https://doi.org/10.3390/ijerph15030519` },
        { level: 'moderate', text: `Earplugs/white noise`, source: `Basner, M., & McGuire, S. (2018). WHO Environmental Noise Guidelines for the European Region: A systematic review on environmental noise and effects on sleep. IJERPH, 15(3), 519. https://doi.org/10.3390/ijerph15030519` },
        { level: 'deep', text: `Consistent quiet environment`, source: `Basner, M., & McGuire, S. (2018). WHO Environmental Noise Guidelines for the European Region: A systematic review on environmental noise and effects on sleep. IJERPH, 15(3), 519. https://doi.org/10.3390/ijerph15030519` },
        { level: 'gentle', text: `No phone in bed`, source: `Edinger, J. D. et al. (2021). Behavioral and psychological treatments for chronic insomnia disorder in adults: AASM systematic review, meta-analysis and GRADE assessment. Journal of Clinical Sleep Medicine, 17(2), 263-298. https://doi.org/10.5664/jcsm.8988` },
        { level: 'moderate', text: `No work in bed`, source: `Edinger, J. D. et al. (2021). Behavioral and psychological treatments for chronic insomnia disorder in adults: AASM systematic review, meta-analysis and GRADE assessment. Journal of Clinical Sleep Medicine, 17(2), 263-298. https://doi.org/10.5664/jcsm.8988` },
        { level: 'deep', text: `Bed only for sleep`, source: `Edinger, J. D. et al. (2021). Behavioral and psychological treatments for chronic insomnia disorder in adults: AASM systematic review, meta-analysis and GRADE assessment. Journal of Clinical Sleep Medicine, 17(2), 263-298. https://doi.org/10.5664/jcsm.8988` },
        { level: 'gentle', text: `Alcohol-free 2 h before bed`, source: `Gardiner, C. L. et al. The effect of alcohol on subsequent sleep in healthy adults: A systematic review and meta-analysis. Sleep Medicine Reviews, 80, 102030. https://doi.org/10.1016/j.smrv.2024.102030` },
        { level: 'moderate', text: `Alcohol-free 3 h before bed`, source: `Gardiner, C. L. et al. The effect of alcohol on subsequent sleep in healthy adults: A systematic review and meta-analysis. Sleep Medicine Reviews, 80, 102030. https://doi.org/10.1016/j.smrv.2024.102030` },
        { level: 'deep', text: `Skip alcohol on weekdays`, source: `Gardiner, C. L. et al. The effect of alcohol on subsequent sleep in healthy adults: A systematic review and meta-analysis. Sleep Medicine Reviews, 80, 102030. https://doi.org/10.1016/j.smrv.2024.102030` },
      ] },
      { name: `Share`, practices: [
        { level: 'gentle', text: `Share one sleep intention`, source: `Gollwitzer, P. M., & Sheeran, P. (2006). Implementation intentions and goal achievement: A meta-analysis. Advances in Experimental Social Psychology, 38, 69-119.
Hennessy, E. A. et al. (2020). Self-regulation mechanisms in health behavior change. Health Psychology Review, 14(1), 6-42. https://doi.org/10.1080/17437199.2019.1679654` },
        { level: 'moderate', text: `Share your bedtime target`, source: `Gollwitzer, P. M., & Sheeran, P. (2006). Implementation intentions and goal achievement: A meta-analysis. Advances in Experimental Social Psychology, 38, 69-119.
Hennessy, E. A. et al. (2020). Self-regulation mechanisms in health behavior change. Health Psychology Review, 14(1), 6-42. https://doi.org/10.1080/17437199.2019.1679654` },
        { level: 'deep', text: `Review together the next day`, source: `Gollwitzer, P. M., & Sheeran, P. (2006). Implementation intentions and goal achievement: A meta-analysis. Advances in Experimental Social Psychology, 38, 69-119.
Hennessy, E. A. et al. (2020). Self-regulation mechanisms in health behavior change. Health Psychology Review, 14(1), 6-42. https://doi.org/10.1080/17437199.2019.1679654` },
        { level: 'gentle', text: `Share one thing that helped`, source: `Spring, B. et al. (2020). Self-regulatory behaviour change techniques in interventions to promote healthy eating, physical activity, or weight loss: a meta-review. Health Psychology Review, 15(4), 508-539.` },
        { level: 'moderate', text: `Share one lesson learned`, source: `Spring, B. et al. (2020). Self-regulatory behaviour change techniques in interventions to promote healthy eating, physical activity, or weight loss: a meta-review. Health Psychology Review, 15(4), 508-539.` },
        { level: 'deep', text: `Weekly Circle reflection`, source: `Spring, B. et al. (2020). Self-regulatory behaviour change techniques in interventions to promote healthy eating, physical activity, or weight loss: a meta-review. Health Psychology Review, 15(4), 508-539.` },
      ] },
      { name: `Celebrate`, practices: [
        { level: 'gentle', text: `Congratulate one teammate`, source: `Mair, J. L. et al. (2023). Effective behavior change techniques in digital health interventions: An umbrella review. Annals of Behavioral Medicine, 57(10), 817-835. https://doi.org/10.1093/abm/kaad041` },
        { level: 'moderate', text: `Celebrate weekly wins`, source: `Mair, J. L. et al. (2023). Effective behavior change techniques in digital health interventions: An umbrella review. Annals of Behavioral Medicine, 57(10), 817-835. https://doi.org/10.1093/abm/kaad041` },
        { level: 'deep', text: `Build a shared streak`, source: `Mair, J. L. et al. (2023). Effective behavior change techniques in digital health interventions: An umbrella review. Annals of Behavioral Medicine, 57(10), 817-835. https://doi.org/10.1093/abm/kaad041` },
      ] },
    ],
  },
  {
    id: 'eat',
    name: 'GoodEat',
    tagline: 'Eat for energy, rhythm, and connection',
    blurb: 'Nourish well, find a steady eating rhythm, and bring presence and people back to the table.',
    accent: 'oklch(0.62 0.2 47)',
    accent2: 'oklch(0.68 0.2 55)',
    soft: 'oklch(0.955 0.055 60)',
    categories: [
      { name: `Nourish`, practices: [
        { level: 'gentle', text: `Add a source of protein to every main meal`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
        { level: 'gentle', text: `Eat two portions of vegetables today`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
        { level: 'gentle', text: `Replace one ultra-processed snack with fruit or nuts`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
        { level: 'gentle', text: `Drink water before each meal`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
        { level: 'moderate', text: `Build every lunch around protein + vegetables`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
        { level: 'moderate', text: `Include legumes or whole grains three times this week`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
        { level: 'moderate', text: `Reach your personal daily protein target`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
        { level: 'moderate', text: `Eat 20 different plant foods during the week`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
        { level: 'deep', text: `Plan all weekday lunches and dinners in advance`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
        { level: 'deep', text: `Avoid ultra-processed foods for five consecutive days`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
        { level: 'deep', text: `Prioritize seasonal and minimally processed ingredients`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
        { level: 'deep', text: `Keep a simple food journal for the entire week`, source: `Morton, R. W. et al. (2018). Systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength.
Hall, K. D. et al. (2019). Ultra-processed diets cause excess calorie intake and weight gain. Cell Metabolism. https://doi.org/10.1016/j.cmet.2019.05.008
Corney, R., Sunderland, C., & James, L. (2016). Immediate pre-meal water ingestion decreases voluntary food intake in lean young males. European Journal of Nutrition.` },
      ] },
      { name: `Rhythm`, practices: [
        { level: 'gentle', text: `Eat breakfast (or first meal) at a consistent time`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'gentle', text: `Avoid eating after 10 pm`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'gentle', text: `Sit down for every main meal`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'gentle', text: `Leave at least 2 hours between dinner and sleep`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'moderate', text: `Keep a consistent 12-hour eating window`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'moderate', text: `Avoid unnecessary snacking between meals`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'moderate', text: `Eat lunch before 2 pm`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'moderate', text: `Finish dinner at roughly the same time every day`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'deep', text: `Maintain your chosen eating window for 30 days`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'deep', text: `Avoid food within 3 hours of bedtime`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'deep', text: `Plan your week's meal schedule every Sunday`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'deep', text: `Reserve one meal each week for slow, uninterrupted eating`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
        { level: 'deep', text: `Intermittent fasting 5 times per week or more`, source: `McHill, A. W., & Wright, K. P. (2017). Role of meal timing in human circadian rhythms.
Iao, S. et al. (2022). Associations between bedtime eating or drinking, sleep duration and wake after sleep onset: findings from the American Time Use Survey.` },
      ] },
      { name: `Presence`, practices: [
        { level: 'gentle', text: `Eat one meal each day without your phone`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
        { level: 'gentle', text: `Take one deep breath before eating`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
        { level: 'gentle', text: `Spend at least 20 minutes on one meal`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
        { level: 'gentle', text: `Notice one flavour you normally overlook`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
        { level: 'moderate', text: `Eat every dinner without screens`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
        { level: 'moderate', text: `Stop eating when comfortably satisfied rather than full`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
        { level: 'moderate', text: `Chew slowly during the first five minutes of each meal`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
        { level: 'moderate', text: `Express gratitude for one aspect of your meal`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
        { level: 'deep', text: `Practice mindful eating for one meal every day`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
        { level: 'deep', text: `Create a pleasant table setting even when eating alone`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
        { level: 'deep', text: `Never multitask while eating`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
        { level: 'deep', text: `End each meal with one reflection on how it made you feel`, source: `Robinson, E. et al. (2013). Eating attentively: a systematic review and meta-analysis of the effect of food intake memory and awareness on eating.
Robinson, E. et al. (2022). Systematic review on distracted eating and energy intake.` },
      ] },
      { name: `Share`, practices: [
        { level: 'gentle', text: `Share one meal this week with a friend, family member or colleague`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Michie, S. et al. (2013). The Behaviour Change Technique Taxonomy.` },
        { level: 'gentle', text: `Exchange one healthy recipe with your Circle`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Michie, S. et al. (2013). The Behaviour Change Technique Taxonomy.` },
        { level: 'gentle', text: `Send a message inviting someone to have coffee or lunch`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Michie, S. et al. (2013). The Behaviour Change Technique Taxonomy.` },
        { level: 'moderate', text: `Organise a healthy lunch or dinner with another person once a week`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Michie, S. et al. (2013). The Behaviour Change Technique Taxonomy.` },
        { level: 'moderate', text: `Cook a meal inspired by a Circle member's recommendation`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Michie, S. et al. (2013). The Behaviour Change Technique Taxonomy.` },
        { level: 'moderate', text: `Eat one meal this week without anyone using a phone at the table`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Michie, S. et al. (2013). The Behaviour Change Technique Taxonomy.` },
        { level: 'moderate', text: `Introduce one meaningful conversation question during a shared meal`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Michie, S. et al. (2013). The Behaviour Change Technique Taxonomy.` },
        { level: 'deep', text: `Host a GoodEat Table with friends or family centred on health and conviviality`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Michie, S. et al. (2013). The Behaviour Change Technique Taxonomy.` },
        { level: 'deep', text: `Invite someone who might otherwise eat alone to join you`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Michie, S. et al. (2013). The Behaviour Change Technique Taxonomy.` },
        { level: 'deep', text: `Share with your Circle one story or lesson from that meal`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Michie, S. et al. (2013). The Behaviour Change Technique Taxonomy.` },
        { level: 'deep', text: `Ask everyone around the table: "What is one thing you hope to give more of to others this year?"`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Michie, S. et al. (2013). The Behaviour Change Technique Taxonomy.` },
      ] },
      { name: `Celebrate`, practices: [
        { level: 'gentle', text: `Cook a family recipe with a younger generation`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Dunbar, R. I. M. (2017). Breaking Bread: The Functions of Social Eating. Adaptive Human Behavior and Physiology, 3, 198-211.` },
        { level: 'moderate', text: `Share a meaningful food memory with your Circle`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Dunbar, R. I. M. (2017). Breaking Bread: The Functions of Social Eating. Adaptive Human Behavior and Physiology, 3, 198-211.` },
        { level: 'moderate', text: `Thank the person who prepared your meal`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Dunbar, R. I. M. (2017). Breaking Bread: The Functions of Social Eating. Adaptive Human Behavior and Physiology, 3, 198-211.` },
        { level: 'deep', text: `Invite someone new to your table`, source: `Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social Relationships and Mortality Risk: A Meta-analytic Review. PLoS Medicine, 7(7), e1000316.
Dunbar, R. I. M. (2017). Breaking Bread: The Functions of Social Eating. Adaptive Human Behavior and Physiology, 3, 198-211.` },
      ] },
    ],
  },
  {
    id: 'move',
    name: 'GoodMove',
    tagline: 'Movement woven through every day',
    blurb: 'Build steady daily movement, strength, and the joy of moving alongside others.',
    accent: 'oklch(0.62 0.155 76)',
    accent2: 'oklch(0.72 0.175 88)',
    soft: 'oklch(0.955 0.06 92)',
    categories: [
      { name: `Incidental Movement & Sedentary Behavior`, practices: [
        { level: 'gentle', text: `7,000 steps / day`, source: `Paluch, A. E., Bajpai, S., Bassett, D. R., Carnethon, M. R., Ekelund, U., Evenson, K. R., Galuska, D. A., Jefferis, B. J., Kraus, W. E., Lee, I. M., Matthews, C. E., Omura, J. D., Patel, A. V., Pieper, C. F., Rees-Punia, E., Dallmeier, D., Klenk, J., Whincup, P. H., Dooley, E. E., Pettee Gabriel, K., … Steps for Health Collaborative (2022). Daily steps and all-cause mortality: a meta-analysis of 15 international cohorts. The Lancet. Public health, 7(3), e219–e228. https://doi.org/10.1016/S2468-2667(21)00302-9` },
        { level: 'moderate', text: `8,000-10,000 steps daily`, source: `Paluch, A. E., Bajpai, S., Bassett, D. R., Carnethon, M. R., Ekelund, U., Evenson, K. R., Galuska, D. A., Jefferis, B. J., Kraus, W. E., Lee, I. M., Matthews, C. E., Omura, J. D., Patel, A. V., Pieper, C. F., Rees-Punia, E., Dallmeier, D., Klenk, J., Whincup, P. H., Dooley, E. E., Pettee Gabriel, K., … Steps for Health Collaborative (2022). Daily steps and all-cause mortality: a meta-analysis of 15 international cohorts. The Lancet. Public health, 7(3), e219–e228. https://doi.org/10.1016/S2468-2667(21)00302-9` },
        { level: 'deep', text: `10,000+ steps daily`, source: `Paluch, A. E., Bajpai, S., Bassett, D. R., Carnethon, M. R., Ekelund, U., Evenson, K. R., Galuska, D. A., Jefferis, B. J., Kraus, W. E., Lee, I. M., Matthews, C. E., Omura, J. D., Patel, A. V., Pieper, C. F., Rees-Punia, E., Dallmeier, D., Klenk, J., Whincup, P. H., Dooley, E. E., Pettee Gabriel, K., … Steps for Health Collaborative (2022). Daily steps and all-cause mortality: a meta-analysis of 15 international cohorts. The Lancet. Public health, 7(3), e219–e228. https://doi.org/10.1016/S2468-2667(21)00302-9` },
        { level: 'gentle', text: `Stand and move for 2 min every hour during work`, source: `Dunstan, D. W., Kingwell, B. A., Larsen, R., Healy, G. N., Cerin, E., Hamilton, M. T., Shaw, J. E., Bertovic, D. A., Zimmet, P. Z., Salmon, J., & Owen, N. (2012). Breaking up prolonged sitting reduces postprandial glucose and insulin responses. Diabetes care, 35(5), 976–983. https://doi.org/10.2337/dc11-1931` },
        { level: 'moderate', text: `Take a 2-3 min walking break every 30 min of sitting`, source: `Dunstan, D. W., Kingwell, B. A., Larsen, R., Healy, G. N., Cerin, E., Hamilton, M. T., Shaw, J. E., Bertovic, D. A., Zimmet, P. Z., Salmon, J., & Owen, N. (2012). Breaking up prolonged sitting reduces postprandial glucose and insulin responses. Diabetes care, 35(5), 976–983. https://doi.org/10.2337/dc11-1931` },
        { level: 'deep', text: `Break sitting every 20-30 min with light or moderate walking, on at least one work block daily`, source: `Dunstan, D. W., Kingwell, B. A., Larsen, R., Healy, G. N., Cerin, E., Hamilton, M. T., Shaw, J. E., Bertovic, D. A., Zimmet, P. Z., Salmon, J., & Owen, N. (2012). Breaking up prolonged sitting reduces postprandial glucose and insulin responses. Diabetes care, 35(5), 976–983. https://doi.org/10.2337/dc11-1931` },
        { level: 'gentle', text: `Take a 10-minute walk after one meal three times this week`, source: `Reynolds AN, Mann JI, Williams S, Venn BJ (2016). Advice to walk after meals is more effective for lowering postprandial glycaemia in type 2 diabetes mellitus than advice that does not specify timing: a randomised crossover study. Diabetologia, 59(12), 2572-2578. https://doi.org/10.1007/s00125-016-4085-2` },
        { level: 'moderate', text: `Take a 10-minute walk after one of your main meals, most days`, source: `Reynolds AN, Mann JI, Williams S, Venn BJ (2016). Advice to walk after meals is more effective for lowering postprandial glycaemia in type 2 diabetes mellitus than advice that does not specify timing: a randomised crossover study. Diabetologia, 59(12), 2572-2578. https://doi.org/10.1007/s00125-016-4085-2` },
        { level: 'deep', text: `Take a 10-minute walk after every main meal, every day`, source: `Reynolds AN, Mann JI, Williams S, Venn BJ (2016). Advice to walk after meals is more effective for lowering postprandial glycaemia in type 2 diabetes mellitus than advice that does not specify timing: a randomised crossover study. Diabetologia, 59(12), 2572-2578. https://doi.org/10.1007/s00125-016-4085-2` },
      ] },
      { name: `Structured Cardio`, practices: [
        { level: 'gentle', text: `10 min of moderate cardio (brisk walk, cycle, swim), 3 times this week`, source: `Bull FC, Al-Ansari SS, Biddle S, Borodulin K, Buman MP, Cardon G, et al. (2020). World Health Organization 2020 guidelines on physical activity and sedentary behaviour. British Journal of Sports Medicine, 54(24), 1451-1462. https://doi.org/10.1136/bjsports-2020-102955` },
        { level: 'moderate', text: `150 min/week of moderate aerobic activity, spread across the week`, source: `Bull FC, Al-Ansari SS, Biddle S, Borodulin K, Buman MP, Cardon G, et al. (2020). World Health Organization 2020 guidelines on physical activity and sedentary behaviour. British Journal of Sports Medicine, 54(24), 1451-1462. https://doi.org/10.1136/bjsports-2020-102955` },
        { level: 'deep', text: `300 min/week of moderate activity, or 75-150 min of vigorous activity`, source: `Bull FC, Al-Ansari SS, Biddle S, Borodulin K, Buman MP, Cardon G, et al. (2020). World Health Organization 2020 guidelines on physical activity and sedentary behaviour. British Journal of Sports Medicine, 54(24), 1451-1462. https://doi.org/10.1136/bjsports-2020-102955` },
        { level: 'gentle', text: `Add one session this week where you get slightly out of breath (brisk incline walk, stairs)`, source: `Mandsager K, Harb S, Cremer P, Phelan D, Nissen SE, Jaber W (2018). Association of Cardiorespiratory Fitness With Long-term Mortality Among Adults Undergoing Exercise Treadmill Testing. JAMA Network Open, 1(6), e183605. https://doi.org/10.1001/jamanetworkopen.2018.3605` },
        { level: 'moderate', text: `One interval-style session/week (e.g. 1 min fast / 2 min easy, x6)`, source: `Mandsager K, Harb S, Cremer P, Phelan D, Nissen SE, Jaber W (2018). Association of Cardiorespiratory Fitness With Long-term Mortality Among Adults Undergoing Exercise Treadmill Testing. JAMA Network Open, 1(6), e183605. https://doi.org/10.1001/jamanetworkopen.2018.3605` },
        { level: 'deep', text: `One structured, near-maximal-effort interval session/week`, source: `Mandsager K, Harb S, Cremer P, Phelan D, Nissen SE, Jaber W (2018). Association of Cardiorespiratory Fitness With Long-term Mortality Among Adults Undergoing Exercise Treadmill Testing. JAMA Network Open, 1(6), e183605. https://doi.org/10.1001/jamanetworkopen.2018.3605` },
        { level: 'gentle', text: `Try one 10-min HIIT-style session this week (20 sec hard / 40 sec easy, repeated)`, source: `Weston KS, Wisløff U, Coombes JS (2014). High-intensity interval training in patients with lifestyle-induced cardiometabolic disease: a systematic review and meta-analysis. British Journal of Sports Medicine, 48, 1227-1234. https://doi.org/10.1136/bjsports-2013-092576` },
        { level: 'moderate', text: `One 15-20 min HIIT session per week`, source: `Weston KS, Wisløff U, Coombes JS (2014). High-intensity interval training in patients with lifestyle-induced cardiometabolic disease: a systematic review and meta-analysis. British Journal of Sports Medicine, 48, 1227-1234. https://doi.org/10.1136/bjsports-2013-092576` },
        { level: 'deep', text: `Two HIIT sessions per week, alongside regular aerobic training`, source: `Weston KS, Wisløff U, Coombes JS (2014). High-intensity interval training in patients with lifestyle-induced cardiometabolic disease: a systematic review and meta-analysis. British Journal of Sports Medicine, 48, 1227-1234. https://doi.org/10.1136/bjsports-2013-092576` },
      ] },
      { name: `Strength & Resistance`, practices: [
        { level: 'gentle', text: `One full-body strength session per week (bodyweight or light weights)`, source: `Saeidifard F, Medina-Inojosa JR, West CP, Olson TP, Somers VK, Bonikowske AR, Prokop LJ, Vinciguerra M, Lopez-Jimenez F (2019). The association of resistance training with mortality: A systematic review and meta-analysis. European Journal of Preventive Cardiology, 26(15), 1647-1665. https://doi.org/10.1177/2047487319850718` },
        { level: 'moderate', text: `2 strength sessions/week covering major muscle groups`, source: `Saeidifard F, Medina-Inojosa JR, West CP, Olson TP, Somers VK, Bonikowske AR, Prokop LJ, Vinciguerra M, Lopez-Jimenez F (2019). The association of resistance training with mortality: A systematic review and meta-analysis. European Journal of Preventive Cardiology, 26(15), 1647-1665. https://doi.org/10.1177/2047487319850718` },
        { level: 'deep', text: `3+ strength sessions/week with progressive overload`, source: `Saeidifard F, Medina-Inojosa JR, West CP, Olson TP, Somers VK, Bonikowske AR, Prokop LJ, Vinciguerra M, Lopez-Jimenez F (2019). The association of resistance training with mortality: A systematic review and meta-analysis. European Journal of Preventive Cardiology, 26(15), 1647-1665. https://doi.org/10.1177/2047487319850718` },
        { level: 'gentle', text: `1 set of 8-12 reps for each major muscle group, once this week`, source: `Ralston GW, Kilgore L, Wyatt FB, Buchan D, Baker JS (2018). Weekly Training Frequency Effects on Strength Gain: A Meta-Analysis. Sports Medicine - Open, 4, 36. https://doi.org/10.1186/s40798-018-0149-9` },
        { level: 'moderate', text: `1 full session/week hitting each muscle group with 2-3 sets`, source: `Ralston GW, Kilgore L, Wyatt FB, Buchan D, Baker JS (2018). Weekly Training Frequency Effects on Strength Gain: A Meta-Analysis. Sports Medicine - Open, 4, 36. https://doi.org/10.1186/s40798-018-0149-9` },
        { level: 'deep', text: `Spread the same weekly volume across 2-3 shorter sessions if preferred`, source: `Ralston GW, Kilgore L, Wyatt FB, Buchan D, Baker JS (2018). Weekly Training Frequency Effects on Strength Gain: A Meta-Analysis. Sports Medicine - Open, 4, 36. https://doi.org/10.1186/s40798-018-0149-9` },
        { level: 'gentle', text: `Add one grip-strength exercise this week (carry a heavy bag, dead-hang, grip trainer)`, source: `Leong DP, Teo KK, Rangarajan S, et al., for the PURE study investigators (2015). Prognostic value of grip strength: findings from the Prospective Urban Rural Epidemiology (PURE) study. The Lancet, 386(9990), 266-273.` },
        { level: 'moderate', text: `Include a grip or carry exercise in 2 sessions this week`, source: `Leong DP, Teo KK, Rangarajan S, et al., for the PURE study investigators (2015). Prognostic value of grip strength: findings from the Prospective Urban Rural Epidemiology (PURE) study. The Lancet, 386(9990), 266-273.` },
        { level: 'deep', text: `Make farmer's carries or dead hangs a regular part of every strength session`, source: `Leong DP, Teo KK, Rangarajan S, et al., for the PURE study investigators (2015). Prognostic value of grip strength: findings from the Prospective Urban Rural Epidemiology (PURE) study. The Lancet, 386(9990), 266-273.` },
      ] },
      { name: `Mobility, Flexibility & Balance`, practices: [
        { level: 'gentle', text: `5-minute mobility flow every morning`, source: `Behm DG, Alizadeh S, Daneshjoo A, Hadjizadeh Anvar S, Graham A, Zahiri A, Goudini R, Edwards C, Culleton R, Scharf C, Konrad A (2023). Acute Effects of Various Stretching Techniques on Range of Motion: A Systematic Review with Meta-Analysis. Sports Medicine - Open, 9, 107.` },
        { level: 'moderate', text: `10 minutes of mobility/stretching, 4 times this week`, source: `Behm DG, Alizadeh S, Daneshjoo A, Hadjizadeh Anvar S, Graham A, Zahiri A, Goudini R, Edwards C, Culleton R, Scharf C, Konrad A (2023). Acute Effects of Various Stretching Techniques on Range of Motion: A Systematic Review with Meta-Analysis. Sports Medicine - Open, 9, 107.` },
        { level: 'deep', text: `Daily 15-minute mobility routine`, source: `Behm DG, Alizadeh S, Daneshjoo A, Hadjizadeh Anvar S, Graham A, Zahiri A, Goudini R, Edwards C, Culleton R, Scharf C, Konrad A (2023). Acute Effects of Various Stretching Techniques on Range of Motion: A Systematic Review with Meta-Analysis. Sports Medicine - Open, 9, 107.` },
        { level: 'gentle', text: `Practice standing on one leg for 20-30 seconds, once a day`, source: `Sherrington C, Fairhall NJ, Wallbank GK, Tiedemann A, Michaleff ZA, Howard K, Clemson L, Hopewell S, Lamb SE (2019). Exercise for preventing falls in older people living in the community. Cochrane Database of Systematic Reviews, Issue 1, Art. No. CD012424. https://doi.org/10.1002/14651858.CD012424.pub2` },
        { level: 'moderate', text: `10 min of balance-challenging exercise (single-leg stands, heel-to-toe walk, tai chi), 2x this week`, source: `Sherrington C, Fairhall NJ, Wallbank GK, Tiedemann A, Michaleff ZA, Howard K, Clemson L, Hopewell S, Lamb SE (2019). Exercise for preventing falls in older people living in the community. Cochrane Database of Systematic Reviews, Issue 1, Art. No. CD012424. https://doi.org/10.1002/14651858.CD012424.pub2` },
        { level: 'deep', text: `3 hours/week of balance-challenging exercise (e.g. a tai chi class or dedicated balance training)`, source: `Sherrington C, Fairhall NJ, Wallbank GK, Tiedemann A, Michaleff ZA, Howard K, Clemson L, Hopewell S, Lamb SE (2019). Exercise for preventing falls in older people living in the community. Cochrane Database of Systematic Reviews, Issue 1, Art. No. CD012424. https://doi.org/10.1002/14651858.CD012424.pub2` },
        { level: 'gentle', text: `Spend 3-5 min warming up (light cardio + dynamic movement) before any structured exercise`, source: `Soligard T, Myklebust G, Steffen K, Holme I, Silvers H, Bizzini M, Junge A, Dvorak J, Bahr R, Andersen TE (2008). Comprehensive warm-up programme to prevent injuries in young female footballers: cluster randomised controlled trial. BMJ, 337, a2469. https://doi.org/10.1136/bmj.a2469` },
        { level: 'moderate', text: `Use a structured warm-up routine before every workout, at least twice this week`, source: `Soligard T, Myklebust G, Steffen K, Holme I, Silvers H, Bizzini M, Junge A, Dvorak J, Bahr R, Andersen TE (2008). Comprehensive warm-up programme to prevent injuries in young female footballers: cluster randomised controlled trial. BMJ, 337, a2469. https://doi.org/10.1136/bmj.a2469` },
        { level: 'deep', text: `Use a comprehensive, injury-prevention-focused warm-up before every session`, source: `Soligard T, Myklebust G, Steffen K, Holme I, Silvers H, Bizzini M, Junge A, Dvorak J, Bahr R, Andersen TE (2008). Comprehensive warm-up programme to prevent injuries in young female footballers: cluster randomised controlled trial. BMJ, 337, a2469. https://doi.org/10.1136/bmj.a2469` },
      ] },
      { name: `Movement Snacking & Self-Monitoring`, practices: [
        { level: 'gentle', text: `Add one 1-2 min burst of vigorous effort into your day (fast stair climb, brisk uphill walk)`, source: `Stamatakis E, Ahmadi MN, Gill JMR, et al. (2022). Association of wearable device-measured vigorous intermittent lifestyle physical activity with mortality. Nature Medicine, 28(12), 2521-2529. https://doi.org/10.1038/s41591-022-02100-x` },
        { level: 'moderate', text: `3 short vigorous bursts (1-2 min each), spread through your day, most days`, source: `Stamatakis E, Ahmadi MN, Gill JMR, et al. (2022). Association of wearable device-measured vigorous intermittent lifestyle physical activity with mortality. Nature Medicine, 28(12), 2521-2529. https://doi.org/10.1038/s41591-022-02100-x` },
        { level: 'deep', text: `Make vigorous incidental bursts a daily habit -- aim for 3+ most days of the week`, source: `Stamatakis E, Ahmadi MN, Gill JMR, et al. (2022). Association of wearable device-measured vigorous intermittent lifestyle physical activity with mortality. Nature Medicine, 28(12), 2521-2529. https://doi.org/10.1038/s41591-022-02100-x` },
        { level: 'gentle', text: `Track your steps for 3 days this week, just to see your baseline`, source: `Bravata DM, Smith-Spangler C, Sundaram V, Gienger AL, Lin N, Lewis R, Stave CD, Olkin I, Sirard JR (2007). Using pedometers to increase physical activity and improve health: a systematic review. JAMA, 298(19), 2296-2304. https://doi.org/10.1001/jama.298.19.2296` },
        { level: 'moderate', text: `Wear a tracker daily and aim to beat your weekly average by 1,000 steps`, source: `Bravata DM, Smith-Spangler C, Sundaram V, Gienger AL, Lin N, Lewis R, Stave CD, Olkin I, Sirard JR (2007). Using pedometers to increase physical activity and improve health: a systematic review. JAMA, 298(19), 2296-2304. https://doi.org/10.1001/jama.298.19.2296` },
        { level: 'deep', text: `Set and track a personal daily step goal every day, adjusting it weekly`, source: `Bravata DM, Smith-Spangler C, Sundaram V, Gienger AL, Lin N, Lewis R, Stave CD, Olkin I, Sirard JR (2007). Using pedometers to increase physical activity and improve health: a systematic review. JAMA, 298(19), 2296-2304. https://doi.org/10.1001/jama.298.19.2296` },
      ] },
      { name: `Social & Accountability`, practices: [
        { level: 'gentle', text: `Join or watch one group activity this month (class, sport, Circle session)`, source: `Burke SM, Carron AV, Eys MA, Ntoumanis N, Estabrooks PA (2005). Group versus individual approach? A meta-analysis of the effectiveness of interventions to promote physical activity. Sport & Exercise Psychology Review. DOI:10.53841/bpssepr.2006.2.1.13` },
        { level: 'moderate', text: `One Circle or group workout this month`, source: `Burke SM, Carron AV, Eys MA, Ntoumanis N, Estabrooks PA (2005). Group versus individual approach? A meta-analysis of the effectiveness of interventions to promote physical activity. Sport & Exercise Psychology Review. DOI:10.53841/bpssepr.2006.2.1.14` },
        { level: 'deep', text: `Lead one movement session for your Circle (even 10 min over video call)`, source: `Burke SM, Carron AV, Eys MA, Ntoumanis N, Estabrooks PA (2005). Group versus individual approach? A meta-analysis of the effectiveness of interventions to promote physical activity. Sport & Exercise Psychology Review. DOI:10.53841/bpssepr.2006.2.1.15` },
        { level: 'gentle', text: `One walk-and-talk call instead of a seated call, this week`, source: `Xu Z, Zheng X, Ding H, Zhang D, Cheung PM-H, Yang Z, Tam KW, Zhou W, Chan DC-C, Wang W, Wong SY-S (2024). The Effect of Walking on Depressive and Anxiety Symptoms: Systematic Review and Meta-Analysis. JMIR Public Health and Surveillance, 10, e48355.
Burke SM, Carron AV, Eys MA, Ntoumanis N, Estabrooks PA (2006), cited under Group Exercise / Circle Workouts.` },
        { level: 'moderate', text: `20-minute walk with a friend or colleague, once a week`, source: `Xu Z, Zheng X, Ding H, Zhang D, Cheung PM-H, Yang Z, Tam KW, Zhou W, Chan DC-C, Wang W, Wong SY-S (2024). The Effect of Walking on Depressive and Anxiety Symptoms: Systematic Review and Meta-Analysis. JMIR Public Health and Surveillance, 10, e48355.
Burke SM, Carron AV, Eys MA, Ntoumanis N, Estabrooks PA (2006), cited under Group Exercise / Circle Workouts.` },
        { level: 'deep', text: `Make walking meetings or calls your default at least 3 times a week`, source: `Xu Z, Zheng X, Ding H, Zhang D, Cheung PM-H, Yang Z, Tam KW, Zhou W, Chan DC-C, Wang W, Wong SY-S (2024). The Effect of Walking on Depressive and Anxiety Symptoms: Systematic Review and Meta-Analysis. JMIR Public Health and Surveillance, 10, e48355.
Burke SM, Carron AV, Eys MA, Ntoumanis N, Estabrooks PA (2006), cited under Group Exercise / Circle Workouts.` },
        { level: 'gentle', text: `Suggest a friendly step-count challenge to one person this month`, source: `Chaudhry UAR, Wahlich C, Fortescue R, Cook DG, Knightly R, Harris T (2020). The effects of step-count monitoring interventions on physical activity: systematic review and meta-analysis of community-based randomised controlled trials in adults. International Journal of Behavioral Nutrition and Physical Activity, 17, 129. https://doi.org/10.1186/s12966-020-01020-8` },
        { level: 'moderate', text: `Join or start a Circle step-count challenge this month, comparing progress weekly`, source: `Chaudhry UAR, Wahlich C, Fortescue R, Cook DG, Knightly R, Harris T (2020). The effects of step-count monitoring interventions on physical activity: systematic review and meta-analysis of community-based randomised controlled trials in adults. International Journal of Behavioral Nutrition and Physical Activity, 17, 129. https://doi.org/10.1186/s12966-020-01020-8` },
        { level: 'deep', text: `Run a full-month Circle step challenge with a shared leaderboard, updated at least weekly`, source: `Chaudhry UAR, Wahlich C, Fortescue R, Cook DG, Knightly R, Harris T (2020). The effects of step-count monitoring interventions on physical activity: systematic review and meta-analysis of community-based randomised controlled trials in adults. International Journal of Behavioral Nutrition and Physical Activity, 17, 129. https://doi.org/10.1186/s12966-020-01020-8` },
        { level: 'gentle', text: `Take at least 1 full rest or light-activity day this week`, source: `Gabbett TJ (2016). The training-injury prevention paradox: should athletes be training smarter and harder? British Journal of Sports Medicine, 50(5), 273-280. https://doi.org/10.1136/bjsports-2015-095788` },
        { level: 'moderate', text: `Plan 1-2 rest/active-recovery days into your weekly routine`, source: `Gabbett TJ (2016). The training-injury prevention paradox: should athletes be training smarter and harder? British Journal of Sports Medicine, 50(5), 273-280. https://doi.org/10.1136/bjsports-2015-095788` },
        { level: 'deep', text: `Structure your week so hard sessions are never scheduled back-to-back`, source: `Gabbett TJ (2016). The training-injury prevention paradox: should athletes be training smarter and harder? British Journal of Sports Medicine, 50(5), 273-280. https://doi.org/10.1136/bjsports-2015-095788` },
      ] },
    ],
  },
  {
    id: 'mind',
    name: 'GoodMind',
    tagline: 'Attention, calm, and connection',
    blurb: 'Train a steadier mind through breath, reflection, and honest connection with others.',
    accent: '#AECE36',
    accent2: 'oklch(0.82 0.17 122)',
    soft: 'oklch(0.95 0.08 120)',
    light: true,
    categories: [
      { name: `Mindfulness & Meditation`, practices: [
        { level: 'gentle', text: `5 min of guided meditation, 3 times this week`, source: `Goyal M, Singh S, Sibinga EMS, et al. (2014). Meditation Programs for Psychological Stress and Well-Being: A Systematic Review and Meta-Analysis. JAMA Internal Medicine, 174(3), 357-368. https://doi.org/10.1001/jamainternmed.2013.13018` },
        { level: 'moderate', text: `10 min of meditation, 4 times this week`, source: `Goyal M, Singh S, Sibinga EMS, et al. (2014). Meditation Programs for Psychological Stress and Well-Being: A Systematic Review and Meta-Analysis. JAMA Internal Medicine, 174(3), 357-368. https://doi.org/10.1001/jamainternmed.2013.13018` },
        { level: 'deep', text: `15-20 min of meditation daily`, explanation: `Research suggests that regular meditation can help reduce stress and improve emotional wellbeing over time. This practice gives you a simple, sustainable way to begin building that habit.`, evidenceSummary: `A systematic review and meta-analysis found that meditation programmes were associated with small to moderate improvements in stress, anxiety and depression symptoms.`, source: `Goyal M, Singh S, Sibinga EMS, et al. (2014). Meditation Programs for Psychological Stress and Well-Being: A Systematic Review and Meta-Analysis. JAMA Internal Medicine, 174(3), 357-368. https://doi.org/10.1001/jamainternmed.2013.13018` },
        { level: 'gentle', text: `2 min of slow, conscious breathing daily`, source: `Ma X, Yue Z-Q, Gong Z-Q, Zhang H, Duan N-Y, Shi Y-T, Wei G-X, Li Y-F (2017). The Effect of Diaphragmatic Breathing on Attention, Negative Affect and Stress in Healthy Adults. Frontiers in Psychology, 8, 874. https://doi.org/10.3389/fpsyg.2017.00874` },
        { level: 'moderate', text: `5 min of slow breathing daily`, source: `Ma X, Yue Z-Q, Gong Z-Q, Zhang H, Duan N-Y, Shi Y-T, Wei G-X, Li Y-F (2017). The Effect of Diaphragmatic Breathing on Attention, Negative Affect and Stress in Healthy Adults. Frontiers in Psychology, 8, 874. https://doi.org/10.3389/fpsyg.2017.00874` },
        { level: 'deep', text: `10 min of paced breathing daily (around 4-6 breaths/min)`, source: `Ma X, Yue Z-Q, Gong Z-Q, Zhang H, Duan N-Y, Shi Y-T, Wei G-X, Li Y-F (2017). The Effect of Diaphragmatic Breathing on Attention, Negative Affect and Stress in Healthy Adults. Frontiers in Psychology, 8, 874. https://doi.org/10.3389/fpsyg.2017.00874` },
        { level: 'gentle', text: `Once today, pause and name what you're doing right now, instead of thinking about something else`, source: `Killingsworth MA, Gilbert DT (2010). A Wandering Mind Is an Unhappy Mind. Science, 330(6006), 932. https://doi.org/10.1126/science.1192439` },
        { level: 'moderate', text: `3 times this week, spend 5 min fully focused on one task without switching`, source: `Killingsworth MA, Gilbert DT (2010). A Wandering Mind Is an Unhappy Mind. Science, 330(6006), 932. https://doi.org/10.1126/science.1192439` },
        { level: 'deep', text: `Build a daily habit of noticing when your mind has wandered and gently returning to the present`, source: `Killingsworth MA, Gilbert DT (2010). A Wandering Mind Is an Unhappy Mind. Science, 330(6006), 932. https://doi.org/10.1126/science.1192439` },
      ] },
      { name: `Cognitive & Emotional Regulation`, practices: [
        { level: 'gentle', text: `Once this week, reframe a strong negative reaction in a more neutral or useful light`, source: `Gross JJ, John OP (2003). Individual Differences in Two Emotion Regulation Processes: Implications for Affect, Relationships, and Well-Being. Journal of Personality and Social Psychology, 85(2), 348-362. https://doi.org/10.1037/0022-3514.85.2.348` },
        { level: 'moderate', text: `Practice reframing a stressful thought 2-3 times this week`, source: `Gross JJ, John OP (2003). Individual Differences in Two Emotion Regulation Processes: Implications for Affect, Relationships, and Well-Being. Journal of Personality and Social Psychology, 85(2), 348-362. https://doi.org/10.1037/0022-3514.85.2.348` },
        { level: 'deep', text: `Make reappraisal your default first response to stress, daily`, source: `Gross JJ, John OP (2003). Individual Differences in Two Emotion Regulation Processes: Implications for Affect, Relationships, and Well-Being. Journal of Personality and Social Psychology, 85(2), 348-362. https://doi.org/10.1037/0022-3514.85.2.348` },
        { level: 'gentle', text: `Once today, name what you're feeling in one or two words`, source: `Lieberman MD, Eisenberger NI, Crockett MJ, Tom SM, Pfeifer JH, Way BM (2007). Putting Feelings Into Words: Affect Labeling Disrupts Amygdala Activity in Response to Affective Stimuli. Psychological Science, 18(5), 421-428. https://doi.org/10.1111/j.1467-9280.2007.01916.x` },
        { level: 'moderate', text: `Daily emotional check-in ("What am I feeling?"), 4 times this week`, source: `Lieberman MD, Eisenberger NI, Crockett MJ, Tom SM, Pfeifer JH, Way BM (2007). Putting Feelings Into Words: Affect Labeling Disrupts Amygdala Activity in Response to Affective Stimuli. Psychological Science, 18(5), 421-428. https://doi.org/10.1111/j.1467-9280.2007.01916.x` },
        { level: 'deep', text: `Daily emotional check-in with a brief note on why, every day`, source: `Lieberman MD, Eisenberger NI, Crockett MJ, Tom SM, Pfeifer JH, Way BM (2007). Putting Feelings Into Words: Affect Labeling Disrupts Amygdala Activity in Response to Affective Stimuli. Psychological Science, 18(5), 421-428. https://doi.org/10.1111/j.1467-9280.2007.01916.x` },
        { level: 'gentle', text: `Next time you're stressed, try talking to yourself using your own name instead of "I"`, source: `Kross E, Bruehlman-Senecal E, Park J, Burson A, Dougherty A, Shablack H, Bremner R, Moser J, Ayduk O (2014). Self-Talk as a Regulatory Mechanism: How You Do It Matters. Journal of Personality and Social Psychology, 106(2), 304-324. https://doi.org/10.1037/a0035173` },
        { level: 'moderate', text: `Use third-person self-talk during 2 stressful moments this week`, source: `Kross E, Bruehlman-Senecal E, Park J, Burson A, Dougherty A, Shablack H, Bremner R, Moser J, Ayduk O (2014). Self-Talk as a Regulatory Mechanism: How You Do It Matters. Journal of Personality and Social Psychology, 106(2), 304-324. https://doi.org/10.1037/a0035173` },
        { level: 'deep', text: `Make third-person self-talk your go-to tool before any high-pressure moment`, source: `Kross E, Bruehlman-Senecal E, Park J, Burson A, Dougherty A, Shablack H, Bremner R, Moser J, Ayduk O (2014). Self-Talk as a Regulatory Mechanism: How You Do It Matters. Journal of Personality and Social Psychology, 106(2), 304-324. https://doi.org/10.1037/a0035173` },
      ] },
      { name: `Digital Boundaries & Attention`, practices: [
        { level: 'gentle', text: `Set a 30-min daily limit on one social media app, 3 days this week`, source: `Hunt MG, Marx R, Lipson C, Young J (2018). No More FOMO: Limiting Social Media Decreases Loneliness and Depression. Journal of Social and Clinical Psychology, 37(10), 751-768. https://doi.org/10.1521/jscp.2018.37.10.751` },
        { level: 'moderate', text: `Limit total social media use to about 30 min/day, most days this week`, source: `Hunt MG, Marx R, Lipson C, Young J (2018). No More FOMO: Limiting Social Media Decreases Loneliness and Depression. Journal of Social and Clinical Psychology, 37(10), 751-768. https://doi.org/10.1521/jscp.2018.37.10.751` },
        { level: 'deep', text: `Limit social media to 10 min per platform per day, every day`, source: `Hunt MG, Marx R, Lipson C, Young J (2018). No More FOMO: Limiting Social Media Decreases Loneliness and Depression. Journal of Social and Clinical Psychology, 37(10), 751-768. https://doi.org/10.1521/jscp.2018.37.10.751` },
        { level: 'gentle', text: `Close extra tabs/apps for one focused task today`, source: `Ophir E, Nass C, Wagner AD (2009). Cognitive Control in Media Multitaskers. Proceedings of the National Academy of Sciences, 106(37), 15583-15587. https://doi.org/10.1073/pnas.0903620106` },
        { level: 'moderate', text: `One hour of distraction-free, single-task work, most days this week`, source: `Ophir E, Nass C, Wagner AD (2009). Cognitive Control in Media Multitaskers. Proceedings of the National Academy of Sciences, 106(37), 15583-15587. https://doi.org/10.1073/pnas.0903620106` },
        { level: 'deep', text: `One hour of distraction-free deep work, daily`, source: `Ophir E, Nass C, Wagner AD (2009). Cognitive Control in Media Multitaskers. Proceedings of the National Academy of Sciences, 106(37), 15583-15587. https://doi.org/10.1073/pnas.0903620106` },
        { level: 'gentle', text: `Turn off notifications for one app today`, source: `Kushlev K, Proulx JDE, Dunn EW (2016). "Silence Your Phones": Smartphone Notifications Increase Inattention and Hyperactivity Symptoms. Proceedings of the 2016 CHI Conference on Human Factors in Computing Systems, 1011-1020. https://doi.org/10.1145/2858036.2858359` },
        { level: 'moderate', text: `Keep phone notifications off during one work block daily`, source: `Kushlev K, Proulx JDE, Dunn EW (2016). "Silence Your Phones": Smartphone Notifications Increase Inattention and Hyperactivity Symptoms. Proceedings of the 2016 CHI Conference on Human Factors in Computing Systems, 1011-1020. https://doi.org/10.1145/2858036.2858359` },
        { level: 'deep', text: `Keep notifications off by default, checking your phone only at set times`, source: `Kushlev K, Proulx JDE, Dunn EW (2016). "Silence Your Phones": Smartphone Notifications Increase Inattention and Hyperactivity Symptoms. Proceedings of the 2016 CHI Conference on Human Factors in Computing Systems, 1011-1020. https://doi.org/10.1145/2858036.2858359` },
      ] },
      { name: `Gratitude & Reflection`, practices: [
        { level: 'gentle', text: `Write 3 things you're grateful for before bed, once this week`, source: `Emmons RA, McCullough ME (2003). Counting Blessings Versus Burdens: An Experimental Investigation of Gratitude and Subjective Well-Being in Daily Life. Journal of Personality and Social Psychology, 84(2), 377-389. https://doi.org/10.1037/0022-3514.84.2.377` },
        { level: 'moderate', text: `Write 3 gratitude lines before bed, most nights this week`, source: `Emmons RA, McCullough ME (2003). Counting Blessings Versus Burdens: An Experimental Investigation of Gratitude and Subjective Well-Being in Daily Life. Journal of Personality and Social Psychology, 84(2), 377-389. https://doi.org/10.1037/0022-3514.84.2.377` },
        { level: 'deep', text: `Write 3 gratitude lines before bed, every night`, source: `Emmons RA, McCullough ME (2003). Counting Blessings Versus Burdens: An Experimental Investigation of Gratitude and Subjective Well-Being in Daily Life. Journal of Personality and Social Psychology, 84(2), 377-389. https://doi.org/10.1037/0022-3514.84.2.377` },
        { level: 'gentle', text: `Write for 5 min about something on your mind, once this week`, source: `Pennebaker JW, Beall SK (1986). Confronting a Traumatic Event: Toward an Understanding of Inhibition and Disease. Journal of Abnormal Psychology, 95(3), 274-281. https://doi.org/10.1037/0021-843X.95.3.274` },
        { level: 'moderate', text: `Journal for 10-15 min, 2-3 times this week`, source: `Pennebaker JW, Beall SK (1986). Confronting a Traumatic Event: Toward an Understanding of Inhibition and Disease. Journal of Abnormal Psychology, 95(3), 274-281. https://doi.org/10.1037/0021-843X.95.3.274` },
        { level: 'deep', text: `Journal for 15 min daily about your thoughts and feelings`, source: `Pennebaker JW, Beall SK (1986). Confronting a Traumatic Event: Toward an Understanding of Inhibition and Disease. Journal of Abnormal Psychology, 95(3), 274-281. https://doi.org/10.1037/0021-843X.95.3.274` },
        { level: 'gentle', text: `Write down 1 good thing that happened today, once this week`, source: `Seligman MEP, Steen TA, Park N, Peterson C (2005). Positive Psychology Progress: Empirical Validation of Interventions. American Psychologist, 60(5), 410-421. https://doi.org/10.1037/0003-066X.60.5.410` },
        { level: 'moderate', text: `Write down 3 good things that happened, 4 days this week`, source: `Seligman MEP, Steen TA, Park N, Peterson C (2005). Positive Psychology Progress: Empirical Validation of Interventions. American Psychologist, 60(5), 410-421. https://doi.org/10.1037/0003-066X.60.5.410` },
        { level: 'deep', text: `Write down 3 good things -- and why they happened -- every day`, source: `Seligman MEP, Steen TA, Park N, Peterson C (2005). Positive Psychology Progress: Empirical Validation of Interventions. American Psychologist, 60(5), 410-421. https://doi.org/10.1037/0003-066X.60.5.410` },
      ] },
      { name: `Social Connection & Vulnerability`, practices: [
        { level: 'gentle', text: `Share one honest, personal thought with someone this week, instead of keeping it to small talk`, source: `Collins NL, Miller LC (1994). Self-Disclosure and Liking: A Meta-Analytic Review. Psychological Bulletin, 116(3), 457-475. https://doi.org/10.1037/0033-2909.116.3.457` },
        { level: 'moderate', text: `Share something a little more personal with 2-3 different people this week`, source: `Collins NL, Miller LC (1994). Self-Disclosure and Liking: A Meta-Analytic Review. Psychological Bulletin, 116(3), 457-475. https://doi.org/10.1037/0033-2909.116.3.457` },
        { level: 'deep', text: `Make sharing something real (not just surface talk) a regular part of your conversations, most days`, source: `Collins NL, Miller LC (1994). Self-Disclosure and Liking: A Meta-Analytic Review. Psychological Bulletin, 116(3), 457-475. https://doi.org/10.1037/0033-2909.116.3.457` },
        { level: 'gentle', text: `Have one extra brief chat today with someone you don't know well (neighbor, barista, colleague)`, source: `Sandstrom GM, Dunn EW (2014). Social Interactions and Well-Being: The Surprising Power of Weak Ties. Personality and Social Psychology Bulletin, 40(7), 910-922. https://doi.org/10.1177/0146167214529799` },
        { level: 'moderate', text: `Chat with 3 different acquaintances or "weak ties" this week, even briefly`, source: `Sandstrom GM, Dunn EW (2014). Social Interactions and Well-Being: The Surprising Power of Weak Ties. Personality and Social Psychology Bulletin, 40(7), 910-922. https://doi.org/10.1177/0146167214529799` },
        { level: 'deep', text: `Make small talk with someone new most days this week`, source: `Sandstrom GM, Dunn EW (2014). Social Interactions and Well-Being: The Surprising Power of Weak Ties. Personality and Social Psychology Bulletin, 40(7), 910-922. https://doi.org/10.1177/0146167214529799` },
        { level: 'gentle', text: `Send one thoughtful message this week to someone you appreciate`, source: `Holt-Lunstad J, Smith TB, Layton JB (2010). Social Relationships and Mortality Risk: A Meta-Analytic Review. PLoS Medicine, 7(7), e1000316. https://doi.org/10.1371/journal.pmed.1000316` },
        { level: 'moderate', text: `One Circle vulnerability check-in weekly (what drained you, what nourished you)`, source: `Holt-Lunstad J, Smith TB, Layton JB (2010). Social Relationships and Mortality Risk: A Meta-Analytic Review. PLoS Medicine, 7(7), e1000316. https://doi.org/10.1371/journal.pmed.1000316` },
        { level: 'deep', text: `Share one personal reflection with your Circle every week`, source: `Holt-Lunstad J, Smith TB, Layton JB (2010). Social Relationships and Mortality Risk: A Meta-Analytic Review. PLoS Medicine, 7(7), e1000316. https://doi.org/10.1371/journal.pmed.1000316` },
      ] },
      { name: `Rest & Restoration`, practices: [
        { level: 'gentle', text: `Spend 20 min outdoors in a green space this week`, source: `White MP, Alcock I, Grellier J, Wheeler BW, Hartig T, Warber SL, Bone A, Depledge MH, Fleming LE (2019). Spending at Least 120 Minutes a Week in Nature Is Associated With Good Health and Wellbeing. Scientific Reports, 9(1), 7730. https://doi.org/10.1038/s41598-019-44097-3` },
        { level: 'moderate', text: `Spend at least 120 min in nature this week, in one or more visits`, source: `White MP, Alcock I, Grellier J, Wheeler BW, Hartig T, Warber SL, Bone A, Depledge MH, Fleming LE (2019). Spending at Least 120 Minutes a Week in Nature Is Associated With Good Health and Wellbeing. Scientific Reports, 9(1), 7730. https://doi.org/10.1038/s41598-019-44097-3` },
        { level: 'deep', text: `Make 120+ min in nature a weekly habit`, source: `White MP, Alcock I, Grellier J, Wheeler BW, Hartig T, Warber SL, Bone A, Depledge MH, Fleming LE (2019). Spending at Least 120 Minutes a Week in Nature Is Associated With Good Health and Wellbeing. Scientific Reports, 9(1), 7730. https://doi.org/10.1038/s41598-019-44097-3` },
        { level: 'gentle', text: `Take one 15-min walk this week and notice one thing that feels vast or amazing`, source: `Sturm VE, Datta S, Roy ARK, Sible IJ, Kosik EL, Veziris CR, Chow TE, Morris NA, Neuhaus J, Kramer JH, Miller BL, Holley SR, Keltner D (2020). Big Smile, Small Self: Awe Walks Promote Prosocial Positive Emotions in Older Adults. Emotion, 22(5), 1044-1058. https://doi.org/10.1037/emo0000876` },
        { level: 'moderate', text: `Take a 15-min "awe walk" once a week, looking for wonder rather than worry`, source: `Sturm VE, Datta S, Roy ARK, Sible IJ, Kosik EL, Veziris CR, Chow TE, Morris NA, Neuhaus J, Kramer JH, Miller BL, Holley SR, Keltner D (2020). Big Smile, Small Self: Awe Walks Promote Prosocial Positive Emotions in Older Adults. Emotion, 22(5), 1044-1058. https://doi.org/10.1037/emo0000876` },
        { level: 'deep', text: `Make a weekly awe walk a standing habit for the month`, source: `Sturm VE, Datta S, Roy ARK, Sible IJ, Kosik EL, Veziris CR, Chow TE, Morris NA, Neuhaus J, Kramer JH, Miller BL, Holley SR, Keltner D (2020). Big Smile, Small Self: Awe Walks Promote Prosocial Positive Emotions in Older Adults. Emotion, 22(5), 1044-1058. https://doi.org/10.1037/emo0000876` },
        { level: 'gentle', text: `Take one evening this week fully off from work-related messages or thoughts`, source: `Sonnentag S (2001). Work, Recovery Activities, and Individual Well-Being: A Diary Study. Journal of Occupational Health Psychology, 6(3), 196-210. https://doi.org/10.1037/1076-8998.6.3.196` },
        { level: 'moderate', text: `One half-day digital/work detox this week`, source: `Sonnentag S (2001). Work, Recovery Activities, and Individual Well-Being: A Diary Study. Journal of Occupational Health Psychology, 6(3), 196-210. https://doi.org/10.1037/1076-8998.6.3.196` },
        { level: 'deep', text: `Protect one full digital/work-free block every week, consistently`, source: `Sonnentag S (2001). Work, Recovery Activities, and Individual Well-Being: A Diary Study. Journal of Occupational Health Psychology, 6(3), 196-210. https://doi.org/10.1037/1076-8998.6.3.196` },
      ] },
    ],
  },
];
